spring.application.name=InfoEdge_UT_Demo
server.port = 6000


spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/ie
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# test - URL 
# http://localhost:6000/app/product/test

